---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-m.7"
generator:
  name: "NewMavenProject"
  group: "shboland"
  artifact: "boot-api"
  version: "1.0.0"
  origin:
    repo: "git@github.com:sybrenboland/boot-api.git"
    branch: "feature/R41"
    sha: "8720159*"
  parameters:
    - "artifactId": "spring-boot-api"
    - "groupId": "org.shboland"
    - "version": "1.0.0"
    - "apiModuleName": "api"
    - "coreModuleName": "core"
    - "persistenceModuleName": "persistence"
    - "domainModuleName": "domain"
    - "databaseModuleName": "db"

